<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
      <ProjectReference Include="..\TUTSportApp.Api\TUTSportApp.Api.csproj" />
    <PackageReference Include="xunit" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="coverlet.collector" />
    <!-- Removed Moq, FluentAssertions, and Microsoft.Extensions.Logging.Abstractions as they are managed centrally -->
    <PackageReference Include="Moq" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TUTSportApp.Application\TUTSportApp.Application.csproj" />
    <ProjectReference Include="..\TUTSportApp.Domain\TUTSportApp.Domain.csproj" />
    <ProjectReference Include="..\TUTSportApp.Infrastructure\TUTSportApp.Infrastructure.csproj" />
  </ItemGroup>

</Project>
